# Configuraci\u00c3\u00b3n de la base de datos MySQL

# Este archivo es utilizado para configurar la conexi\u00c3\u00b3n a la base de datos en el archivo DatabaseConnection.java.
# Se debe copiar y pegar en esta misma carpeta con el nombre db.properties
# Luego se debe modificar el archivo db.properties con los datos de conexi\u00c3\u00b3n correctos para su base de datos.

# Aclaraci\u00c3\u00b3n: estos valores son de ejemplo.

db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3307/tpi_pedidos?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
db.user=root
db.password=2610
